export const actionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    CHANGE_QUANTITY: 'CHANGE_QUANTITY',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
    ADD_BILL: 'ADD_BILL',
    REMOVE_BILL: 'REMOVE_BILL'
}